---
language: node_js

sudo: false

cache:
  directories:
    - node_modules
    - bower_components

install:
  - npm install
  - npm install -g bower
  - bower install

script:
  - ./node_modules/.bin/karma start --single-run